name: filter_image_django
services:
  rbas-db:
    image: postgres:11
    ports:
      - 5432
    environment:
      - POSTGRES_USER=pguser
      - POSTGRES_PASSWORD=pgpass
      - POSTGRES_DB=pgdb
  
  filter_image_django:
    public: true
      image:okteto.dev/simple-rbas:latest
    build: .
    replicas: 1
    command: bash -c "gunicorn filter_image_django.wsgi --reload -b 0.0.0.0:8000"
    ports:
      - 8000

    environment:
        - DJANGO_READ_DOT_ENV_FILE=true
        - DATABASE_URL=postgresql://pguser:pgpass@notes-db:5432/pgdb
        - COOKIE_SECURE=true
        - DEBUG=false
