name: filter-image-django
services:

  rbas-db:
    image: postgres:11
    ports:
      - 5432
    environment:
      - POSTGRES_USER=pguser
      - POSTGRES_PASSWORD=pgpass
      - POSTGRES_DB=filterimgdb
    resources:
      cpu: 100m
      memory: 128Mi
  filter_image_django:
    public: true
    image: okteto.dev/filter_image_django:latest
    build: .
    replicas: 1
    command: bash -c "gunicorn filter_image_django.wsgi --reload -b 0.0.0.0:8000"
    ports:
      - 8000
